name: "semantic-segmentation-infer"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "input",
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_INT64
    dims: [ 1, -1, -1 ]
  } 
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching { }
version_policy: { all { }}